dblp:
  url: https://dblp.org/search/publ/api?q={}&format=json&h=1000
  topics:
    - "Domain%20Adaptation%20image%20classification"
    - "Adversarial%20Learning"
    - "unsupervised%20domain%20adaptation%20data%20augmentation"
    - "domain%20%feature%alignment"
    - "feature%20disentanglement"
