dblp:
  url: https://dblp.org/search/publ/api?q={}&format=json&h=1000
  topics:
    - "many-task%20optimization"
    - "manytask%20optimization"
    - "multi-task%20optimization"
    - "multitasking%20optimization"
  mails:
    - "xxzhang_official@163.com"
